version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    entrypoint: /app/entrypoint.sh
    depends_on:
      - db
    env_file:
      - .env  # Ensures environment variables are loaded

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dataa
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
